require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/enrolments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Enrolment. As you add validations to Enrolment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Enrolment.create! valid_attributes
      get enrolments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      enrolment = Enrolment.create! valid_attributes
      get enrolment_url(enrolment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_enrolment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      enrolment = Enrolment.create! valid_attributes
      get edit_enrolment_url(enrolment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Enrolment" do
        expect {
          post enrolments_url, params: { enrolment: valid_attributes }
        }.to change(Enrolment, :count).by(1)
      end

      it "redirects to the created enrolment" do
        post enrolments_url, params: { enrolment: valid_attributes }
        expect(response).to redirect_to(enrolment_url(Enrolment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Enrolment" do
        expect {
          post enrolments_url, params: { enrolment: invalid_attributes }
        }.to change(Enrolment, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post enrolments_url, params: { enrolment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested enrolment" do
        enrolment = Enrolment.create! valid_attributes
        patch enrolment_url(enrolment), params: { enrolment: new_attributes }
        enrolment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the enrolment" do
        enrolment = Enrolment.create! valid_attributes
        patch enrolment_url(enrolment), params: { enrolment: new_attributes }
        enrolment.reload
        expect(response).to redirect_to(enrolment_url(enrolment))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        enrolment = Enrolment.create! valid_attributes
        patch enrolment_url(enrolment), params: { enrolment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested enrolment" do
      enrolment = Enrolment.create! valid_attributes
      expect {
        delete enrolment_url(enrolment)
      }.to change(Enrolment, :count).by(-1)
    end

    it "redirects to the enrolments list" do
      enrolment = Enrolment.create! valid_attributes
      delete enrolment_url(enrolment)
      expect(response).to redirect_to(enrolments_url)
    end
  end
end
